### PR TITLE
Better U2F Support Detection

### LINKED ISSUE #165: Report Firefox as a supported browser if the extension is installed
Currently the Google U2F JS library fails the U2F API version detection on Firefox with the [U2F Support extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) enabled.

See #117 and #163.

### PR DESCRIPTION
**Pull request by kasparsd**
Fixes #165.

Unfortunately there is no official way to detect U2F API support in web browsers. However, in reality only Chrome and Firefox can support U2F.

Chrome supports U2F natively via [`chrome.runtime.sendMessage()`](https://github.com/georgestephanis/two-factor/blob/8b03e926aeee703d8368b108040342f48538592b/includes/Google/u2f-api.js#L196-L206) so we can simply check for `chrome.runtime` and assume that it does support U2F.

The [Firefox U2F extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) works by [creating a global `window.u2f` object](https://github.com/prefiks/u2f4moz/blob/ab97706a178a3299a6568bab7dcdd320108c870f/ext/data/content-script.js#L120) that maps to its internal functions. So we check if `window.u2f` exists before adding the wrapper in `u2f-api.js`.

## Chrome

chrome-ok

## Firefox with Extension

firefox-ok

## Safari

safari-fail

### CODE REVIEW

File: includes/Google/u2f-api.js [hunk 1]
```diff
@@ -17,6 +17,12 @@
 var u2f = u2f || {};
 
 /**
+ * Check if browser supports U2F API before this wrapper was added.
+ * @type {int}
+ */
+u2f.HasNativeApiSupport = ( ( u2f && u2f.register ) || ( chrome && chrome.runtime ) );
```
Comment (kasparsd) [inline includes/Google/u2f-api.js]: `u2f.register` should exist in Firefox with the extension enabled before we add our own `u2f.register` wrapper further down this file.

**Comment by kasparsd** [comment]
@georgestephanis This can also be merged.
